### ISSUE TITLE
some odd emcee problem?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/mcmc#30]
Probably my fault, but:
```
[dhogg@electric-avenue MCMC]$ make
true
(echo "Looking into problems:"; cd problems; /Applications/Xcode.app/Contents/Developer/usr/bin/make ) 
Looking into problems:
python -W ignore rosenbrock2.py
Traceback (most recent call last):
  File "rosenbrock2.py", line 24, in <module>
    coords, _, _ = sampler.run_mcmc(coords, 10000, progress=True)
  File "/anaconda/lib/python3.6/site-packages/emcee/sampler.py", line 172, in run_mcmc
    **kwargs):
TypeError: sample() got an unexpected keyword argument 'progress'
make[1]: *** [rosenbrock2.pdf] Error 1
make: *** [problems] Error 2
```

**Comment by dfm** [comment]
You need to update to the GitHub master.

**Comment by dfm** [comment]
pip install https://github.com/dfm/emcee/archive/develop.zip
