### ISSUE TITLE
emcee showing unexpected Typeerror.

### ISSUE THREAD

**Issue by nidhinrhna** [davidwhogg/mcmc#34]
I tried an emcee simulation in my laptop and is getting this unusual error. Is it due to version incompatibility?

>>> %Run MULT_FREQ_updated.py
FREQUENCY:  28
Traceback (most recent call last):
  File "/media/soumen/Elements/WORK/WORK_ON_CMBBH/ROUND1/PSM_SIMULATION_MULTI_CHANNEL_NIDHIN/MULT_FREQ_updated.py", line 108, in <module>
    pos,prob,state = sampler.run_mcmc(p0, 1000,progress=True)
  File "/home/soumen/.thonny/Python36/lib/python3.6/site-packages/emcee/sampler.py", line 172, in run_mcmc
    **kwargs):
TypeError: sample() got an unexpected keyword argument 'progress'

**Comment by davidwhogg** [comment]
I think you meant to put this against emcee?
